### PR TITLE
[3.x] Add ability to purge queues

### PR DESCRIPTION
**Pull request by parkourben99**
Add the ability to purge individual queues with a confirmation.

Fixes https://github.com/laravel/horizon/issues/328

image

image

### CODE REVIEW

**Comment by aaronheath** [comment]
Looks promising. Would love some tests.

**Comment by tomswinkels** [comment]
Wow, cool!!!!

**Comment by tim-hanssen** [comment]
Nice! We really need some feature like this 💃

**Comment by driesvints** [comment]
@parkourben99 thanks. Can you squash your commits and revert the compiled assets? We'll compile these ourselves before tagging a release.

**Comment by taylorotwell** [comment]
The jobs will still display on the recent jobs and failed jobs screens.

**Comment by themsaid** [comment]
> The jobs will still display on the recent jobs and failed jobs screens.

As Taylor mentioned, people will still see these jobs and will get confused.

**Comment by parkourben99** [comment]
> The jobs will still display on the recent jobs and failed jobs screens.

@taylorotwell Would it be better to show these jobs have been purged in the ui or remove them completely?

**Comment by taylorotwell** [comment]
It seems like you would not want to see them at all anymore.

**Comment by parkourben99** [comment]
@driesvints I have added the suggestion from Taylor and written some tests. What are your thoughts?

**Comment by driesvints** [comment]
@parkourben99 Taylor will review this once he gets to it. Thanks 👍

**Comment by themsaid** [comment]
@parkourben99 Your solution will cause the pagination to break in the Recent Jobs and Failed Jobs screens. You're deleting Jobs from the memory but they are still referenced in `recent_jobs` and `failed_jobs` sorted sets, you'll need to clean the sets.

Also purging a busy queue will cause the redis instance to wait until all the `DEL` commands are run, it's better to run a single DEL with all the keys.

**Comment by taylorotwell** [comment]
As this has some problems that likely can't be solved easily I am going to table this for now.

**Comment by tomswinkels** [comment]
Hard to hear... I hope that @parkourben99 can fix the issues and this PR than can be merged :)

**Comment by tomswinkels** [comment]
@parkourben99 some update?

**Comment by parkourben99** [comment]
@tomswinkels I'll update with the suggested changes and make a new PR soon 👍

**Comment by tomswinkels** [comment]
@parkourben99 very nice, i will wait for that :)

**Comment by tomswinkels** [comment]
I have thinking about this and maybe it is better to move the purge button to a queue detail view.

**Comment by parkourben99** [comment]
What are you thinking should be on this detail view page?

**Pull request closed without merging**
