### PR TITLE
[5.x] A fresh coat of paint

### PR DESCRIPTION
**Pull request by jessarcher**
This PR freshens up Horizon with the same changes made to Telescope at https://github.com/laravel/telescope/pull/1295. This includes new colors, icons, fonts, shadows, sizing, spacing, alignment, and other miscellaneous improvements.

The main differences in this PR are:

* Using Tailwind's violet palette instead of indigo to match Horizon's branding.
* Horizon has a few extra UI components, such as the dashboard stats, which have all been freshened.

### Before

image

### After

image

### Before

image

### After

image

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thank you! 🔥

**Comment by GC-Mark** [comment]
Great work 👍 

Any plans for a Mobile UI?

**Comment by driesvints** [comment]
We don't have any plans for mobile, sorry.

**Comment by benholmen** [comment]
@jessarcher just upgraded some dependencies and it was a sweet surprise to see the redesign! Looks great, thank you!

**Pull request merged**
