### PR TITLE
Allow horizon to use all the width

### PR DESCRIPTION
**Pull request by ludo237**
This little change allows horizon to gain advantage of the entire browser width and being consistent with other layout~~s~~ such as ~~Telescope and~~ Nova

### CODE REVIEW

**Comment by ludo237** [comment]
@browner12 You are right but Horizon, especially the "recent jobs" tab, could really benefit from a fluid container because otherwise the card will look ugly and too thin

**Comment by taylorotwell** [comment]
Can you send a screenshot of what you are trying to fix... basically show me what it looks like now that isn't working for you?

**Comment by browner12** [comment]
...and let us know what screen dimensions you're viewing it at

**Comment by ludo237** [comment]
Sure, incoming (sorry for delay, timezone is different 🤣 )

**Comment by ludo237** [comment]
Ok so basically the problem is in either "Failed Jobs" and "Recent Jobs":

image

The tab gets a scroll bar and everything you have to move it across to check other table columns

Now with container fluid you get a nice wide table and all the columns fit perfectly, it doesn't break the other pages for example the Dashboard will remain clean and all but with a wide cards in it.

**Comment by themsaid** [comment]
We're planning a frontend overhaul for Horizon soon where all of the reported issues will be fixed.

**Comment by ludo237** [comment]
@themsaid well, that's awesome. Then I guess I can close this issue for now.

**Comment by robclancy** [comment]
@themsaid come on... making it use full width is a very easy change, it doesn't even give you a scrollbar for when things are too wide (which is every page for us). And 3+ month overhaul shouldn't be stopping the current thing from getting a simple normal feature.

**Comment by themsaid** [comment]
@robclancy sorry been working on other stuff. Will look into the overhaul soon.

**Comment by robclancy** [comment]
@themsaid an overall can take however long, but current version using such little screen space meaning a lot of UI isn't even shown is an issue I have to deal with everytime I use horizon in production. Or post a workaround? It's frustrating to come back to this issue often and see it's just ignored because of an overhaul in the future which will take much longer since it requires actual detailed work. A width change is a width change...

**Comment by robclancy** [comment]
@themsaid ...

**Comment by driesvints** [comment]
@robclancy work has begun on the new Horizon update in the meantime :)

**Comment by ludo237** [comment]
@robclancy stop being a jerk. This is a FOSS project if you really need that fast help with a PR or wait.

**Comment by driesvints** [comment]
@ludo237 since this PR which does just that was closed a new PR wouldn't really help...

We ask for everyone's patience a little while longer while we work on the new version.

**Comment by robclancy** [comment]
@ludo237 lmao... this is the PR, how do you not know this? You made it... which has no negative affects and should have just been merged instead of waiting months for a big update.

I love selecting text to make it scroll right so I can see a full error though, it's great.

**Pull request closed without merging**
