### PR TITLE
Empty message if loading finished

### PR DESCRIPTION
**Pull request by iamzozo**
* According to other components, check the loading also to display the empty message
* Add /.idea to gitignore

### CODE REVIEW

**Comment by taylorotwell** [comment]
@themsaid is this ok?

**Comment by browner12** [comment]
@iamzozo FYI, you can also use the global gitignore:

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by iamzozo** [comment]
Thanks! I was thinking about the ignore, but saw Thumbs.db and .DS_Store are also in.

**Comment by themsaid** [comment]
yes it's fine, merged and recompiled assets

**Pull request merged**
