### PR TITLE
float times

### PR DESCRIPTION
**Pull request by halaei**
Reopnning #188 
#188 was closed because you claimed some breaking change that I could not find. Could you please help me figuring it out in this PR? Thanks

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't remember where the exact bug report came from. @themsaid might?

**Comment by themsaid** [comment]
@halaei can you please explain what was this fixing?

**Comment by halaei** [comment]
This pr adds decimal precision to seconds in the graphs, making them more meaningful. I sent an example screenshot here: https://github.com/laravel/horizon/pull/188#issuecomment-335424627

**Comment by taylorotwell** [comment]
Most likely the bug report came to us via Twitter or some other social channel.

**Comment by halaei** [comment]
I am confused a bit. Did you revisit #188?
The pr is just an improvement not a bug fix. @themsaid told that something calculation went wrong after compiling and testing that  pr. Then I couldn't find what was wrong 🤔 but everything was fine to me.

**Comment by halaei** [comment]
A question about backward compatibility. Should every change work without the user forced to do artisan vendor:publish again?

**Comment by taylorotwell** [comment]
I'm not sure. If this is merged, what do users have to do to get it to work properly?

**Comment by halaei** [comment]
Then users should run `php artisan vendor:publish --force --tag=horizon-assets` after update.

PS: If this is merged, you have to compile assets in another commit/PR. I didn't commit them here because I don't think developers other than package maintainers are supposed to do that. Besides there was a bug somewhere related to UglifyJs and I was not able to compile for production. Please see https://github.com/laravel/horizon/issues/307

**Comment by themsaid** [comment]
@halaei I still think something is wrong with this PR, once I merge it my graphs change and start showing non-sense. Maybe your graph doesn't appear broken for your jobs runtime is in a specific range.

**Comment by halaei** [comment]
I'll test it more with slower jobs and send before/after screenshots if I couldn't find the issue.

**Comment by halaei** [comment]
I see nothing wrong here except if the users don't run vendor:publish they may/may not see the charts because of the wrong selected scales. After publish everything looks fine.
Please note that the charts after merge and publish are supposed to descend a second or less, but not more.

### Queue metrics before PR:
before-queue-1

### Queue metrics after merge before vendor:publish --force:
during-queue-1

### Queue metrics after merge and vendor:publish --force:
after-queue-1
 
### Job metrics before PR: 
before-job-1

### Job metrics after merge before vendor:publish --force:
during-job-1

### Job metrics after merge and vendor:publish --force:
after-job-1

**Comment by taylorotwell** [comment]
@themsaid you're still having problems with this?

**Comment by themsaid** [comment]
@taylorotwell I'll test it again in the morning and share my findings.

**Comment by francislavoie** [comment]
What's the holdup on this one? I have a fork of horizon just for the purposes of this change. I'd appreciate this getting merged so I can stop using my fork and have to use a github API key with composer :stuck_out_tongue:

**Comment by francislavoie** [comment]
Thank you @taylorotwell! :tada:

**Comment by halaei** [comment]
@taylorotwell Please note that I didn't compile the assets in the PR because I was not sure if I should do so.

**Comment by arjankapteijn** [comment]
Although i already did a 'php artisan vendor:publish --force --tag=horizon-assets', the Runtime metrics are empty after the update from v1.2.3 to v1.3.0.

schermafbeelding 2018-06-21 om 09 46 07

Any suggestions in how to fix this?

**Comment by halaei** [comment]
@arjankapteijn That is because assets are not compiled yet :(

**Comment by themsaid** [comment]
v1.3.1 was pushed with assets compiled.

**Pull request merged**
