### PR TITLE
[5.x] Added ability to set local environment

### PR DESCRIPTION
**Pull request by 0xb4lint**
With this PR you can set the `local_env` configuration option.
It defaults to the currently hardwired `local` value, so there is no breaking change.

### CODE REVIEW

**Comment by driesvints** [comment]
Imo this isn't needed. It's meant to be a sensible default for the 99% use case of apps. If you have a different environment name for your local environment just configure the gate.

**Comment by 0xb4lint** [comment]
In this case my apps belong to the 1%. 😉 
I understand I can override this behavior in my `HorizonServiceProvider` (and `Horizon::check()` will follow), but I think I would be nice not to hardwire it.
Of course it's your call.

**Comment by driesvints** [comment]
What's your use case for changing the default local env name?

**Comment by 0xb4lint** [comment]
I'm using branch names as environments (some kind of git flow), so in my case the `develop` is the "local" environment.

It wasn't a problem for ages, but I've just checked the Laravel framework code and I see there's 2 reference to `local` environment (`Application::isLocal()` and `TrustHosts::shouldSpecifyTrustedHosts()`). 

So I understand this is the expected behavior in Laravel, sorry for taking your time. 😉

**Comment by driesvints** [comment]
@0xb4lint no sorry needed. Good luck with your app 👍

**Pull request closed without merging**
