### PR TITLE
Monitor tags by clicking on the tag within the Recent Jobs screen

### PR DESCRIPTION
**Pull request by tplaner**
Creates buttons out of each of the job tags listed on the Recent Jobs screen.

Upon clicking one of these tags it will begin monitoring that tag and redirect you to the Monitoring screen.

### CODE REVIEW

**Comment by themsaid** [comment]
This might break the style when the number of tags is a bit large since each tag is now rendered as a button.

**Comment by tplaner** [comment]
This is what it looks like:

image

**Comment by themsaid** [comment]
@taylorotwell what do you think?

IMO if we're going to add this at least a confirmation modal should appear to the user so that knows whats going on.

**Comment by taylorotwell** [comment]
Going to hold off for now.

**Pull request closed without merging**
