### PR TITLE
Base-encode job metrics slug to prevent slashes or backslashes pre-ur…

### PR DESCRIPTION
**Pull request by goestijn**
…l-decoders (e.g. azure appservices) can interpret as request_uri segment

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is it possible the slug would contain non-Latin characters which would fail on `btoa`?

**Comment by driesvints** [comment]
Another thought: would existing urls still work?

**Comment by goestijn** [comment]
The latest commit has replaced the depreciated `btoa` function in js with the `Buffer` class which does also supports non-Latin characters.

**Comment by taylorotwell** [comment]
I don't know that I really want to mess with this on patch release.

**Pull request closed without merging**
