### PR TITLE
Respect the prefers-color-scheme setting

### PR DESCRIPTION
**Pull request by ramonrietdijk**
I've changed the layout file to include media attributes on the CSS files in order to respect the `prefers-color-scheme`-setting. The style of Horizon will therefore be determined by the preference of the user. Developers who prefer Horizon in light mode are not affected by the `Horizon::night()` method anymore.

Note that the `night` method has not been removed to prevent a breaking change.

### CODE REVIEW

**Comment by driesvints** [comment]
I think this is a good step but maybe we should take it further and add a toggle like on the Laravel docs so people can choose either light, dark or system preferences?

**Comment by ramonrietdijk** [comment]
Agreed, it would offer a lot more flexibility

**Comment by driesvints** [comment]
Can you add a screenshot how this looks?

**Comment by ramonrietdijk** [comment]
This is how it currently looks:
image

**Comment by driesvints** [comment]
I'd personally remove the background but other than that lgtm. Thanks!

**Review by driesvints — APPROVED** [review]

**Comment by taylorotwell** [comment]
LGTM - thanks 👍

**Comment by lloricode** [comment]
Maybe adding `@deprecated` to a `night()` will will stop using this in future?

**Pull request merged**
