### PR TITLE
Ability to make authorization by gate

### PR DESCRIPTION
**Pull request by slavarazum**
Provide ability to **Horizon** dashboard access by gate. Like it possible in **Nova** and **Telescope**.
```php
Gate::define('viewHorizon', function ($user) {
    return true;
});
```

### CODE REVIEW

**Comment by slavarazum** [comment]
Looks like 1.0 branch has some unmerged into `master` commits. Should we add these commits into `master` branch?

**Comment by driesvints** [comment]
Yes but let's do that in a different PR. I'll send one in in a bit.

**Comment by driesvints** [comment]
@slavarazum done: https://github.com/laravel/horizon/pull/419

Once it gets merged, feel free to send in a PR to master.

**Comment by slavarazum** [comment]
@driesvints Ok, got it.

**Comment by driesvints** [comment]
@slavarazum actually, you're free to branch off from master and send in a pr that way. Don't think you'll have conflicts that way

**Comment by slavarazum** [comment]
@driesvints Yep, it should be ok. Have done - https://github.com/laravel/horizon/pull/420

**Pull request closed without merging**
