### PR TITLE
[2.0] Prevent horizontal scrolling in Dashboard supervisors section

### PR DESCRIPTION
**Pull request by halaei**

### CODE REVIEW

**Comment by themsaid** [comment]
Please share a screenshot of how this is broken

**Comment by halaei** [comment]
screenshot from 2019-02-06 18-30-57

**Comment by taylorotwell** [comment]
So, why exactly do we want to prevent horizontal scrolling there? What does the new behavior look like?

**Comment by driesvints** [comment]
@halaei can you post a screenshot of the new behavior?

**Comment by halaei** [comment]
I just needed to know balancing in a glance. I don't actually care how it should be fixed; maybe some css styling does it too.
screenshot from 2019-02-08 16-04-18

**Comment by driesvints** [comment]
@halaei Thanks!

**Pull request merged**
