### PR TITLE
[2.0] Added auto refresh interval for dashboard

### PR DESCRIPTION
**Pull request by tomswinkels**
There are difference issues about the interval. 

You can change the interval so that you can see faster what is going on.

The name "Auto-refresh interval" is the same as on Beanstalk.

image

### CODE REVIEW

**Comment by driesvints** [comment]
@tomswinkels you might want to give more explanation because otherwise the pr will just be closed.

**Comment by tomswinkels** [comment]
@driesvints there are difference issues about this. You can change the interval so that you can see faster what is going on.

The name is the same as on Beanstalk.

image

**Comment by driesvints** [comment]
I meant that Taylor will close any issues without a clear description in the first comment.

**Comment by tomswinkels** [comment]
Later we can add this to the other pages.

**Comment by taylorotwell** [comment]
I would prefer us to just choose a good convention and have less configuration.

**Comment by tomswinkels** [comment]
@taylorotwell But check the issues. Not everyone would the same. In my case i wan't to see it more live than now. In Beanstalk the default is 500ms.

**Pull request closed without merging**
