### PR TITLE
[3.x] Add Horizon FlushCommand

### PR DESCRIPTION
**Pull request by driesvints**
This adds a new Horizon FlushCommand which will clear the meta data of Horizon from its Redis connection. Kudos to @freekmurze for the inspiration.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What exactly does this flush. Would be helpful to put that in the command description.

**Comment by driesvints** [comment]
It basically resets all the data that's being kept in Redis for the dashboard of Horizon. Basically flushes the connection set by the `horizon.use` config setting. I've pushed a commit which hopefully clarifies this.

**Comment by mfn** [comment]
It's a pretty dangerous thing to do.

Let's not forget how many people have been bitten that when using the Redis cache driver, `artisan cache:clear` also performs a flushdb; after which you hoped you haven't "shared" your redis database with something else => like the workers.

Not sure this is **needed** for horizon. IMHO the PR description doesn't really make a case for "why", also cites someone regarding inspiration?!

**Comment by driesvints** [comment]
@mfn @freekmurze told me he uses this on every Horizon project he builds. It's also imo a command only to be used locally (hence the confirmable trait). It gives you a nice way to clear the dashboard to start fresh when testing locally.

Please also note that this only flushes the Redis "horizon" connection and not your other Redis connections. The "horizon" connection is instantiated by default by Horizon and only keeps the dashboard meta data.

**Comment by fitztrev** [comment]
Just tested this.

> It's also imo a command only to be used locally (hence the confirmable trait).

It's not prompting. Missing the `$this->confirmToProceed()` check.

> Please also note that this only flushes the Redis "horizon" connection and not your other Redis connections.

By default, the `horizon.use` config is the `default` connection. This would also flush anything else that uses that default connection (cache, queue). Could have unintentional effects.

**Comment by driesvints** [comment]
> It's not prompting. Missing the $this->confirmToProceed() check.

Right! Thanks for mentioning this. Added this.

> By default, the horizon.use config is the default connection. This would also flush anything else that uses that default connection (cache, queue). Could have unintentional effects.

I was indeed wrong about this. This will indeed flush anything from the default connection. As I said, this should only be used locally and not in production. Consider it as "migrate:fresh" but for Horizon :)

**Comment by fitztrev** [comment]
> I was indeed wrong about this. This will indeed flush anything from the default connection. As I said, this should only be used locally and not in production. Consider it as "migrate:fresh" but for Horizon :)

If the flush affects more than just Horizon, then I think having it under the `horizon:` artisan namespace is confusing.

**Comment by driesvints** [comment]
@fitztrev I don't agree. It makes use of the connection defined for Horizon. Plus like I said this only needs to be used locally.

**Comment by fitztrev** [comment]
The default connection for Horizon is `default`, which is the same as queue workers and the cache. By default, there is no separate `horizon` connection. And it's not mentioned anywhere to set one up. So `horizon:flush`, under all the default settings, will do more than what its command signature says. That's why I think it would be confusing.

Could the horizon metric keys be tagged instead and then *only* those keys are deleted as opposed to flushing the entire db?

**Comment by mfn** [comment]
> Could the horizon metric keys be tagged instead and then _only_ those keys are deleted as opposed to flushing the entire db?

afaik they are, they've a common prefix: but this requires _iterating_ over keys which is a performance issue in Redis with a *lots of keys*.

I still think this is too dangerous and generally not needed :|

**Comment by driesvints** [comment]
> there is no separate horizon connection. 

Actually, I'm not sure anymore. There is a separate connection set here, which is being used (with a prefix):

https://github.com/laravel/horizon/blob/2c328cbd3ef0fe1e69971cadff6e0cf522cb3bcd/src/Horizon.php#L103

So as I understand it, even though it's the same Redis database, it uses a separate prefix for storing the horizon data. So if you did a flush on that, wouldn't it just flush the data that's prefixed and leave the rest alone?

> I still think this is too dangerous and generally not needed :|

I disagree. Like I said a couple of times above, you would only be using this in development :)

**Comment by fitztrev** [comment]
No, it flushes the entire database--not just things prefixed with `horizon:`

**Comment by taylorotwell** [comment]
I'll just hold off on this for now. If people want to flush something Redis related they can just run FLUSHDB in the Redis console already.

**Pull request closed without merging**
