### PR TITLE
Avoid Server Perf Issues

### PR DESCRIPTION
**Pull request by dbpolito**
Related to #211 and #303.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Needs full description and explanation.

**Comment by MarkVesterskov** [comment]
I've experienced this issue several times as well, especially in a Homestead environment where the Ajax response is often much slower than 5 seconds.

**Comment by themsaid** [comment]
thanks :)

**Comment by williansebastiao** [comment]
Hello guys!
My problem was solved, it was a configuration that was conflicting with the horizon. after that, it worked normally without any errors.
Thanks for listening

**Comment by CImrie** [comment]
@williansebastiao do you mind sharing how you fixed your configuration?

**Comment by williansebastiao** [comment]
Hello @CImrie !
I had some problems:
1 - memory
2 - mysql running with application
3 - bad configuration of nginx

After separating mysql from the application, you have already addressed the problem. then I went in pieces.

**Pull request merged**
