### PR TITLE
Add provider step to readme file

### PR DESCRIPTION
**Pull request by ybaruchel**
Added instructions on how to add the `Laravel\Horizon\HorizonServiceProvider::class` to app.php providers array.

### CODE REVIEW

**Comment by alexbowers** [comment]
Not needed. This is aiming at Laravel 5.5, which has auto-discovery.

**Comment by sudiptpa** [comment]
@ybaruchel you may have to explain a bit more about Laravel 5.5 will have auto-discovery but if you want to install horizon on previous version of laravel on 5.x, like that with your changes.

**Comment by thecrypticace** [comment]
This may be aimed at 5.5 but the composer.json file actually says it supports 5.4:
```json
"illuminate/contracts": "~5.4",
"illuminate/queue": "~5.4",
"illuminate/support": "~5.4",
```

My guess is that's a typo. Maybe it was originally developed on 5.4 but now requires 5.5?

**Comment by taylorotwell** [comment]
Indeed it isn't necessary on 5.5.

**Pull request closed without merging**
