### PR TITLE
[5.x] Update to bootstrap 5.1 and drop jQuery

### PR DESCRIPTION
**Pull request by mmachatschek**
This is the backported version of PR #1119 

Visual comparison:

Before:

Bildschirmfoto 2024-04-04 um 21 30 58

After: 

Bildschirmfoto 2024-04-04 um 21 31 06

before:
Bildschirmfoto 2024-04-04 um 21 31 27

after:

Bildschirmfoto 2024-04-04 um 21 31 38

before:

Bildschirmfoto 2024-04-04 um 21 31 52

after:

Bildschirmfoto 2024-04-04 um 21 31 58

### CODE REVIEW

**Comment by mmachatschek** [comment]
@driesvints this is the resubmitted version of PR https://github.com/laravel/horizon/pull/1119

I currently don't have a full horizon setup available so I can not test this thoroughly enough. If you are ok with that, I could leave it open to others to pick up the work and add the final touches.

I explicitly set the bootstrap version to v5.1 as I originally only did the changes for boostrap v5.1, the 5.2 changes can be made in a followup PR by others. although I think maybe for v6 a complete overhaul with a new tailwind made ui is probably the way to go

**Comment by driesvints** [comment]
Hey @mmachatschek. Thank you for your efforts. I unfortunately also don't have the time atm. Would be great if anyone could help out here.

**Comment by mmachatschek** [comment]
@driesvints i setup two basic laravel horizon apps on my side and pointed to the same horizon process just with different published versions of the ui. The visual comparison is fairly the same (after some tiny modifications) now.

Generally bootstrap made the ui a little bit denser so thats kind of a good point.

From my side its now ready for review

**Review by driesvints — APPROVED** [review]
@mmachatschek thanks for your efforts!

**Comment by driesvints** [comment]
@mmachatschek might be a bit too much for you but any chance you can undo all of these indenting changes in the vue files etc? Would make this PR a whole lot smaller and easier to review.

**Comment by mmachatschek** [comment]
@driesvints sorry about that, VScode applies auto formatting. I convert the PR to draft and reapply the changes. A checked-in prettier config would be nice so that editors automatically pick that up and don't mess up the code

**Comment by driesvints** [comment]
@mmachatschek yeah we don't have a default one because we don't use prettier directly but styleci

**Review by driesvints — APPROVED** [review]
Think this is a good update. Thanks @mmachatschek

**Pull request merged**
