### PR TITLE
[5.x] Added localization

### PR DESCRIPTION
**Pull request by andrey-helldar**
Added the ability to localize the interface.

For example, for French:

image

image

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Sorry, I can't fix codestyle errors because I don't have access to the site ☹️

image

**Comment by andrey-helldar** [comment]
VPN helped solve the problem. It was only necessary to find the right country.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by andrey-helldar** [comment]
@taylorotwell, in fact, it would be cool to use all parts of the multilingual application, including Horizon, but without this functionality, this step is impossible, unfortunately.

If you are confused by writing code, then it is made by analogy with Nova, and the mixin file is directly taken from it.

**Comment by darakanoit** [comment]
Please consider including this in the package

**Comment by arman-arif** [comment]
It would be great if this feature is implemented!

**Pull request closed without merging**
