### PR TITLE
Display worker CPU and memory utilization in supervisor list

### PR DESCRIPTION
**Pull request by AJenbo**
So here is my first PR in relation to #586

This adds information about how much system resources (CPU and memory) the workers are currently consuming:
image

I have tried to communicate this in the most user friendly way possible, but here are some additional details:
 - CPU Threads shows how many logical CPU cores the workers are currently occupying, if the number is close to the actual number of logical CPU cores then the system is probably being maxed out by the workers. Other process will also take resources, so this is not meant to show you system load but rather how much is being used by the workers. As such if the server is doing other tasks it might not be a replacement for other devops tools.
- Memory, this shows how much memory is currently being used by the workers. This is shown as a percentage of total system memory.

### CODE REVIEW

**Comment by driesvints** [comment]
Heya, thank you for working on this! I'm going to have to ask you to resubmit however without the compiled assets. We don't allow this for reasons stated here: https://laravel.com/docs/5.8/contributions#compiled-assets

Make sure that you don't have any commits added with compiled assets and feel free to resubmit. Thanks! :)

**Comment by driesvints** [comment]
Also: if I'm correct I don't immediately see any breaking changes so you may send this to the latest active branch (3.0).

**Comment by AJenbo** [comment]
Ok, no problem I'm not used to dealing with compiled assets :)

I thought this might be considered a new feature so that's why I targeted master, but cool to hear this is small enough to go in to the latest branch.

I don't know if it's against your normal work flow, but if you prefer I can also just update an existing PR instead of creating a new PR.

**Comment by driesvints** [comment]
The new PR is fine.

Most of Laravel's libraries (except the framework and Lumen) are SemVer so new features can still be added on a minor release.

**Pull request closed without merging**
