### PR TITLE
Base path configuration

### PR DESCRIPTION
**Pull request by mikebautista**
This is a cleaned up version of https://github.com/laravel/horizon/pull/216

We are needing a way to use Horizon when it isn’t at the root of the domain. This is the solution we came up with and thought it would be useful for other situations similar to ours.

All you have to do is modify `$base_path` in the `config/horizon.php` file. It is set to empty in case you don’t need to use Horizon in a sub-directory.

It has been tested both at the root and subdirectory use cases. All views and API calls/responses work as expected.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think I'm going to hold off on this for now.

**Comment by b00f** [comment]
When do you think you can merge this PR?

**Comment by eduarguzher** [comment]
It should be re-considered IMO, is there a temporal workaround?

**Comment by jhoff** [comment]
We're currently having to maintain our own fork so that we can use horizon on projects that aren't in the root. Maybe someday ¯\\\_(ツ)\_/¯

**Comment by emparker** [comment]
A bit dirty but i published the assets and change the routes in app.js file in public folder and it works :-D

**Comment by eduarguz** [comment]
Hi @driesvints In case you have some time... what are your thoughts on this?

**Comment by driesvints** [comment]
@eduarguz I'll try to send something in for this. We can definitely make this happen now.

**Pull request closed without merging**
