### PR TITLE
[2.0] Code style fixes

### PR DESCRIPTION
**Pull request by mvdnbrk**
Did my best to make the code base a bit more readable and consistent 😃

### CODE REVIEW

**Comment by mfn** [comment]
What tool did you use to format it?

**Comment by mvdnbrk** [comment]
@mfn Just used my eyes 😄

**Comment by mfn** [comment]
Oh, k. Does that make even sense? Shouldn't this use something like prettier with a config file included in the repo?

**Comment by mvdnbrk** [comment]
@mfn probably it should.

I gave it a try with prettier and a config file in the first place.
That gave some unexpected results. 
That's the reason why I went over all the files and fixed most of the changes by hand.

I am aware that it might not be perfect (yet). 
It is at least a start to get the code a bit more readable and consistent though.

**Comment by taylorotwell** [comment]
Would prefer we do this using an actual tool with reproducable results in the future.

**Pull request closed without merging**
