### PR TITLE
microseconds in metrics

### LINKED ISSUE #187: Metrics in microseconds
The metrics graphs are all usually flat to 0 or 1. I thing supporting microseconds will be good unless you expect the jobs to usually run more than 10 seconds?

### PR DESCRIPTION
**Pull request by halaei**
The metrics graphs are all usually flat to 0 or 1. I thing supporting microseconds will be good unless you expect the jobs to usually run more than 10 seconds?

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you post a screenshot of what this looks like when graphed?

**Comment by themsaid** [comment]
screen shot 2017-10-09 at 7 42 51 pm

This graph shows the runtime of a job that run while we were on the 1.0 branch, it should show 2 seconds, now after switching to this PR and compiling assets it shows 0.02 seconds as runtime, it appears something in the calculations gets mixed up.

**Comment by taylorotwell** [comment]
Yes, this appears to be a breaking change for any existing applications that already have graphs. Feel free to re-submit if you have a way to fix that.

**Comment by halaei** [comment]
img_20171009_212959

studio_20171009_213257

 Here are my screenshots. They are correct but guess I messed something up in jobs' graphs.

**Comment by halaei** [comment]
@themsaid Are you sure the graph was incorrect? For me it is correct!

P.S: It is great to see the performance impact of an update :smile: 
screenshot from 2017-10-10 13-29-54

**Pull request closed without merging**
