### PR TITLE
[5.x] Fix #1419

### LINKED ISSUE #1419: BatchesController missing check for existence of batch
### Horizon Version

5.24.2

### Laravel Version

11.2.0

### PHP Version

8.3.4

### Redis Driver

PhpRedis

### Redis Version

6.0.2

### Database Driver & Version

_No response_

### Description

If you try to access a batch that is not existent (in the database) or call any action like retry the xhr response is a 500 (Attempt to read property "failedJobIds" on null).

The batch retrieval checks for the existence before calling toBatch
```
public function find(string $batchId)
{
        $batch = $this->connection->table($this->table)
                            ->useWritePdo()
                            ->where('id', $batchId)
                            ->first();

        if ($batch) {
            return $this->toBatch($batch);
        }
}
```

but show or retry just assume the batch is existent.
```
public function show($id)
{
        $batch = $this->batches->find($id);

        $failedJobs = app(JobRepository::class)
                        ->getJobs($batch->failedJobIds);

        return [
            'batch' => $batch,
            'failedJobs' => $failedJobs,
        ];
}

public function retry($id)
{
        $batch = $this->batches->find($id);

        app(JobRepository::class)
                        ->getJobs($batch->failedJobIds)
                        ->reject(function ($job) {
                            $payload = json_decode($job->payload);

                            return isset($payload->retry_of);
                        })->each(function ($job) {
                            dispatch(new RetryFailedJob($job->id));
                        });
}
```

### Steps To Reproduce

Access any batch url via horizon that is not existent.

i.e:
/horizon/batches/9bc9d622-c2d0-45ca-aa13-4e7dfb1efed0

### PR DESCRIPTION
**Pull request by tmayrand**
Fixes #1419

Updates to the BatchesController `show()` and `retry()` functions to prevent 500 XHR responses.

### CODE REVIEW

**Comment by driesvints** [comment]
Wouldn't a 404 status code be more applicable here?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by tmayrand** [comment]
@taylorotwell - From a consistency standpoint, other pages in the dashboard do not expose the exception that the batch preview does when the ID is not found.

horizon500

I don't normally work with Vue, so not sure if the 500s (or 404s to Dries' point) in the console are normal or intended behavior. If that is the case, my mistake, I have more to learn.

**Comment by driesvints** [comment]
I still want to try to get this one in tbh as this has come up before... the errors just don't sit right imo. @tmayrand so what does the screen look like if we apply the changes from this PR?

**Comment by tmayrand** [comment]
@driesvints - Nothing appears in console. The rendered page does not change and still displays "Loading..." 

### Batch preview
image

Consistent with all the job preview screens:

#### Pending
image

#### Completed
image

#### Silenced
image

#### Failed
image

**Comment by driesvints** [comment]
@tmayrand I think ideally we'd want to show a "not found" error message but that could be a bigger project. I agree that for now it's best to be consistent with other screens and then maybe improve things with a dedicated 404 message in a different PR.

**Comment by driesvints** [comment]
@taylorotwell gonna re-open this again for the reasons above. Right now, the behaviour here isn't wanted (500 server errors in the console log). This PR makes the behaviour consistent with other not found resources. I think we should merge this.

**Review by driesvints — APPROVED** [review]

**Pull request merged**
