### PR TITLE
[3.0] Absolute to Dynamic resource paths conversion

### PR DESCRIPTION
**Pull request by darki73**
Allow Horizon to load resources from dynamic path rather than absolute

### CODE REVIEW

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient **explanation**, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** **explanation** of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by Frozire** [comment]
@darki73 Did you find another solution or do you want someone to reopen this pull request with an explanation?

We are running into the same issue.

**Comment by darki73** [comment]
@Frozire I guess Mr. @taylorotwell closed this pull request due to missing tests and lack of explanation. This is the one (and probably the only) solution to the existing problem, i am not going to reopen this pull request, for now, i am just using the script which alters the horizon source after it is installed/updated to achieve desired result. Already posted twice about this issue (first PR was submitted couple of months ago), seems like there is no interest in the resolution of that problem, or "probably you have your web server configured incorrectly, please check your server settings first". Just cant be bothered with that issue anymore since found solution which works for me.

**Comment by driesvints** [comment]
@darki73 there is interest in this but you missed the PR guidelines:

> Pull requests without a descriptive title, **thorough description**, or tests will be closed.

Please provide a thorough description when submitting prs and not just link to an issue. It's impossible for Taylor to also go through each issue thread for every pull request he needs to review each day (which are quite a bit).

**Comment by darki73** [comment]
@driesvints thank you for that explanation. May i just "copy/paste" some parts of the issue in new PR to highlight main changes and problems which this PR fixes to help Mr. Taylor Otwell to decide whether or not it is a "worthy" PR?

**Comment by driesvints** [comment]
> May i just "copy/paste" some parts of the issue in new PR to highlight main changes and problems which this PR fixes

Sure thing! As long as the explanation is clear about what it fixes.

> every repo has different requirements

Every Laravel repo should have the same PR guidelines template.

**Comment by darki73** [comment]
@driesvints I was talking about any other open source project on github, wish everyone was using the same "template" for submitting a PR. 

I've created new pull request with required information, do you think that should be enough or should i elaborate more on some parts of it? PR https://github.com/laravel/horizon/pull/638

**Comment by driesvints** [comment]
@darki73 that looks good.

**Pull request closed without merging**
