### PR TITLE
[3.x] Ability to view job details in recent jobs overview

### PR DESCRIPTION
**Pull request by Cannonb4ll**
I sometimes find myself in a situation where I need to know what data is passed into the job (whatever its status was).

This is similar to reading failed job data in the Failed Jobs tab.

Img
Img

### CODE REVIEW

**Comment by driesvints** [comment]
@Cannonb4ll this looks really good 👍 

I was thinking that maybe we can also tackle https://github.com/laravel/horizon/issues/388 together with this? Maybe in a new "Tags" panel below the "Data" pannel? How does the "Tags" data now look in the first panel with lots and lots of tags as displayed in the issue?

**Comment by Cannonb4ll** [comment]
@driesvints Oh dear, I have not checked how it would look with a lot of tags. I will check this, please wait before merging as I could do some nice stuff with this 👏

Will send new updates in this PR.

**Comment by Cannonb4ll** [comment]
@driesvints What do you think of this?

The overview shows a max of 3 tags, and then if there's more than 3 it will show (50 more). The job detail view (which I created earlier) will then also show the tags via vue-pretty-print at the bottom.

I have also added a collapse feature (default from bootstrap, does not come with any additional libs) to make it more easier to quickly read the tags card if you have a lot of data.

See screenshots below for reference, let me know what you think!

img
img2

**Comment by themsaid** [comment]
There will always be people who want to see all tags in the table even if the layout isn't the best, specially that one tag name can already break the layout if it's really long `App\Forge\Servers\Networking\FirewallRules\Rule:12341`.

**Comment by driesvints** [comment]
@Cannonb4ll I've talked to @themsaid about this and it's best that we do the tags box in a different PR. Can you revert your last commit and send in a separate PR for it once this one is merged? Thanks!

**Comment by Cannonb4ll** [comment]
Reverted.

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
@Cannonb4ll feel free to send in a follow up pr!

**Comment by Cannonb4ll** [comment]
@driesvints I would, but then probably only for the tags on the job detail, not the index I think? As @themsaid did not agree on limiting results on the index.

**Comment by driesvints** [comment]
@Cannonb4ll feel free to send in pr with the changes to the index you made.

**Comment by brunogaspar** [comment]
@Cannonb4ll Noticed a small issue, if the job hasn't run or is running, the completed at shows `1970-01-01 01:00:00` :)

I can try to send a pr to address the issue tomorrow or so, just letting you know in case you want to fix it, not a big deal for now hehe

**Comment by Cannonb4ll** [comment]
No need, thats fixed in #755

If that wont be merged ill send it in loose.

**Pull request merged**
