### PR TITLE
[4.x] Added "Attempts" to jobs lists.

### PR DESCRIPTION
**Pull request by piotrgrabowskielastique**
Added "Reserved" icon to indicate which job is being processed and added "Reserved" icon to indicate which job is being processed. This helps debugging bigger queues.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Please share a screenshot.

**Comment by piotrgrabowskielastique** [comment]
image (3)

This isnt the most beautiful icon, couse its exacly the same as the "retry" one in failedJobs.vue (plus "fill-info spin" classes)

**Comment by brunogaspar** [comment]
It could use something like a clock, which means it's still scheduled, just an idea to make it different.

**Comment by piotrgrabowskielastique** [comment]
> It could use something like a clock, which means it's still scheduled, just an idea to make it different.

this might be another PR, couse this spinning icon is indicating that the worker is processing the job. Im not a graphic artist :(

**Comment by taylorotwell** [comment]
I'm confused... can you screenshot all of the icon states now and show which one is which?

**Comment by piotrgrabowskielastique** [comment]
image (4)
You are right, that icon is confusing, so i changed it to a simple spinning gear with fill-primary.

**Comment by driesvints** [comment]
This solves https://github.com/laravel/horizon/issues/686 right?

**Comment by piotrgrabowskielastique** [comment]
> This solves #686 right?

yes, its just diffrent icon :)

**Comment by piotrgrabowskielastique** [comment]
Is there anything thats blocking this feature from being merged in?

**Comment by taylorotwell** [comment]
@piotrgrabowskielastique me taking the time to review it and approve it. 👍

**Pull request merged**
