### PR TITLE
Add date for older jobs

### PR DESCRIPTION
**Pull request by uber1337**
This is related to #133.

I added date  for jobs older than today in order to easy identify when the issue happened.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Has conflicts.

**Comment by taylorotwell** [comment]
@themsaid can you fix this?

**Comment by themsaid** [comment]
@taylorotwell yes but the reason why we don't show date is to make the table more compact.

**Comment by pdewit** [comment]
@themsaid Yeah I agree, that's why I noted in issue #133 that it might be best to be able to see it on mouseover or something similar.

**Pull request closed without merging**
