### PR TITLE
Ability to register horizon routes and pass middleware

### PR DESCRIPTION
**Pull request by themsaid**
Instead of Authenticating the user using a closure, this PR allows publishing Horizon routes using `Horizon::routes()`, then you can pass middleware.

```
Horizon::routes('auth')
```

Or

```
Horizon::routes('auth.is_admin')
```

---

### CODE REVIEW

**Comment by ConnorVG** [comment]
This makes no sense, why not just do _exactly what *Passport* does_? It provides so much more control and keeps the "Laravel package usage" more generic.

**Comment by themsaid** [comment]
@ConnorVG what control do you need? I personally believe the existing `Horizon:: auth()` is enough, I only opened this PR to allow using middleware even tho I truly believe it's not necessary.

**Comment by scrwdnet** [comment]
@themsaid you mentioned you don't believe middleware is necessary, curious as to how **you** would recommend getting the logged in user inside the `Horizon::auth()` closure? Example would be lovely 😍

**Comment by themsaid** [comment]
@scrwdnet 

```
Horizon::auth(function ($request) {
    return auth()->check();
});
```

This will prevent a guest from accessing Horizon.


```
Horizon::auth(function ($request) {
    return auth()->user()->email == 'jon@targaryen.xo';
});
```

This will grant access to only `Jon`

**Comment by scrwdnet** [comment]
@themsaid I have my `Horizon::auth()` call in `AppServiceProvider@boot` and `auth()->user()` always returns `null`.

#GoTSpoilers

**Comment by themsaid** [comment]
@scrwdnet we fixed that in https://github.com/laravel/horizon/pull/68

Make sure you have the latest code

**Comment by taylorotwell** [comment]
I think Horizon::auth is fine for now.

**Comment by scrwdnet** [comment]
@themsaid no composer updates, has that been released yet? I'm at v0.1.0 - shall I move this to an issue?

**Comment by themsaid** [comment]
@scrwdnet we'll issue a release soon.

**Comment by scrwdnet** [comment]
Thanks @themsaid

**Comment by taylorotwell** [comment]
Still prefer to keep it as-is. This exposes Horizon on production by default and forces writing of your own middleware. Open to other solutions if possible.

**Pull request closed without merging**
