### PR TITLE
Trim monitored tag sorted sets, not `monitored_jobs`

### PR DESCRIPTION
**Pull request by benholmen**
This PR addresses [issue 1314](https://github.com/laravel/horizon/issues/1314): for each monitored tag, the redis sorted set containing the timestamp and job ID would grow without trimming. `monitored_jobs` was trimmed, but seems unused so I removed it to avoid confusion.

### CODE REVIEW

**Comment by driesvints** [comment]
@benholmen seems the tests fail here. Can you fix those before proceeding?

**Comment by benholmen** [comment]
Thanks @driesvints @taylorotwell!

I like being able to monitor recent jobs - we use it for troubleshooting recent product imports, webhook processing, etc, which is more effective if it's always available. If we turned it on as needed we'd be missing some context.

How do you want to proceed? Do you want me to add tests to this PR and keep it moving forward, or do you want to go a different direction?

**Comment by driesvints** [comment]
Thanks @benholmen. Remember to mark a PR as ready for review if you want an answer from @taylorotwell.

**Comment by benholmen** [comment]
Thanks @driesvints! I'll do that next time.

**Comment by taylorotwell** [comment]
Personally I would rather not break existing use cases so going to table this for now.

**Pull request closed without merging**
